import { Mood, QuoteType } from './types';

const VERSION_QUERY = '?v=68';
const GITHUB_BASE = 'https://raw.githubusercontent.com/gillemosai/5TASK/refs/heads/main/assets/';

export const AVATAR_IMAGES: Record<Mood, string> = {
  [Mood.HAPPY]: `${GITHUB_BASE}einstein-happy.png${VERSION_QUERY}`,
  [Mood.THINKING]: `${GITHUB_BASE}einstein-skeptical.png${VERSION_QUERY}`,
  [Mood.EXCITED]: `${GITHUB_BASE}einstein-ecstatic.png${VERSION_QUERY}`,
  [Mood.SHOCKED]: `${GITHUB_BASE}einstein-worried.png${VERSION_QUERY}`,
};

export const LOGO_URL = `${GITHUB_BASE}5task-logo.png${VERSION_QUERY}`;

export const QUOTES: Record<QuoteType, string[]> = {
  welcome: [
    "A imaginação é mais importante que o conhecimento! Vamos trabalhar?",
    "Não tenho talentos especiais, sou apenas apaixonadamente curioso.",
    "A mente que se abre a uma nova ideia jamais volta ao seu tamanho original.",
    "O tempo é relativo, mas sua produtividade não precisa ser.",
    "No meio da dificuldade encontra-se a oportunidade.",
    "A lógica leva você de A a B. A imaginação leva você a qualquer lugar.",
    "Deus não joga dados com o universo, e você não deve jogar com seu foco.",
    "A medida da inteligência é a capacidade de mudar.",
    "Uma pessoa que nunca cometeu um erro nunca tentou nada novo.",
    "Tudo deve ser feito da forma mais simples possível, mas não simplista.",
    "A vida é como andar de bicicleta. Para manter o equilíbrio, você deve seguir em frente.",
    "Temos o destino que merecemos. O seu destino começa com a primeira tarefa.",
    "Procure ser uma pessoa de valor, em vez de procurar ser uma pessoa de sucesso.",
    "A criatividade é a inteligência se divertindo. Vamos nos divertir?",
    "O segredo da criatividade é saber como esconder suas fontes.",
    "A distinção entre passado, presente e futuro é apenas uma ilusão teimosa.",
    "Penso 99 vezes e nada descubro. Deixo de pensar e a verdade me é revelada.",
    "O valor do homem é determinado pelo que ele dá e não pelo que ele recebe.",
    "Grandes espíritos sempre encontraram oposição violenta de mentes medíocres.",
    "O mundo é um lugar perigoso para se viver, por causa daqueles que fazem o mal.",
    "Eu não sei com que armas a Terceira Guerra será lutada, mas a quarta será com paus e pedras.",
    "A paz não pode ser mantida à força. Só pode ser alcançada pela compreensão.",
    "A única coisa que interfere no meu aprendizado é a minha educação.",
    "Se você quer uma vida feliz, amarre-a a uma meta, não a pessoas ou coisas.",
    "A percepção do desconhecido é a mais bela experiência que podemos ter.",
    "Informação não é conhecimento. Conhecimento vem da execução.",
    "A teoria é quando se sabe tudo e nada funciona. A prática é quando tudo funciona.",
    "Somente aqueles que tentam o absurdo conseguem alcançar o impossível.",
    "Nunca memorize algo que você possa consultar. Mas estas tarefas você deve focar!",
    "Eu nunca penso no futuro. Ele chega rápido demais.",
    "A única fonte de conhecimento é a experiência. Comece a experimentar agora.",
    "Para ser um membro imaculado de um rebanho de ovelhas, deve-se ser uma ovelha.",
    "A fraqueza de atitude torna-se fraqueza de caráter.",
    "O gênio é 1% talento e 99% trabalho duro. Vamos ao trabalho!",
    "Existem apenas duas maneiras de viver a vida: como se nada fosse um milagre ou tudo fosse.",
    "Se A é o sucesso, então A = X + Y + Z. Trabalho, lazer e manter a boca fechada.",
    "Qualquer tolo inteligente consegue fazer coisas maiores e complexas. Mas focar em 5 é arte.",
    "A natureza nos mostra apenas o rabo do leão. Vamos ver o leão inteiro hoje?",
    "Não tente ser bem sucedido, tente ser valioso.",
    "Se não puder explicar algo de forma simples, você não entendeu bem o suficiente.",
    "O aprendizado é o que fica depois que esquecemos o que aprendemos na escola.",
    "Não podemos resolver problemas usando o mesmo tipo de pensamento de quando os criamos.",
    "A realidade é meramente uma ilusão, embora uma muito persistente.",
    "Onde o mundo cessa de ser o palco de nossas esperanças e desejos pessoais, lá começa a ciência.",
    "Estudar o universo é como ler um livro que não termina. O mesmo vale para o seu potencial.",
    "As leis da matemática, enquanto se referem à realidade, não são certas.",
    "O mistério é a coisa mais bonita que podemos experimentar.",
    "O homem que é capaz de pensar por si mesmo não pode ser um membro da massa.",
    "Todo homem é um gênio. Mas se julgar um peixe por subir em árvores, ele será infeliz.",
    "A questão é: o que você está fazendo com a sua existência agora?",
    "Nenhum problema pode ser resolvido pelo mesmo estado de consciência que o criou.",
    "Saber onde procurar é metade do caminho para o sucesso.",
    "Siga a sua curiosidade, ela é a sua bússola quântica.",
    "Não se preocupe com suas dificuldades em matemática, as minhas são maiores.",
    "A ciência sem religião é manca, a religião sem ciência é cega.",
    "Tudo é energia e isso é tudo o que há. Sincronize com a frequência que deseja.",
    "Não guarde nada na cabeça que possa ser guardado no papel ou neste app.",
    "A vida é uma preparação para o futuro, e a melhor preparação é o foco no presente.",
    "A felicidade não é um objetivo, é o subproduto de uma vida bem vivida.",
    "Nós, mortais, somos apenas passageiros em um trem que corre para o desconhecido."
  ],
  add: [
    "Excelente! O único lugar onde o sucesso vem antes do trabalho é no dicionário.",
    "Mais uma tarefa? A vida é como andar de bicicleta, você deve se manter em movimento.",
    "Foco total! No meio da dificuldade encontra-se a oportunidade.",
    "Uma nova variável na nossa equação de produtividade!",
    "Gostei! A curiosidade é o caminho para o conhecimento.",
    "Matéria adicionada ao sistema. Vamos processar esses fótons!",
    "Brilhante! O universo acaba de ganhar uma nova prioridade.",
    "Excelente escolha. O foco é a lente que incendeia o papel.",
    "Uma mente ocupada é uma mente saudável. Vamos lá!",
    "Cada tarefa adicionada é um passo contra a entropia.",
    "A energia desta lista está aumentando. Sinto os elétrons vibrando!",
    "Magnífico! O plano está se materializando diante de nossos olhos.",
    "Esta tarefa tem o peso de uma pequena estrela. Vamos brilhar!",
    "Adicionado! A teoria é boa, mas a execução é fundamental.",
    "Mais uma meta? Sua determinação é uma constante universal.",
    "Estou impressionado. Sua lista está ganhando massa crítica.",
    "O espaço-tempo acaba de ser reservado para este compromisso.",
    "Interessante... Essa tarefa parece desafiar a lei da inércia.",
    "Muito bem! Um objetivo sem um plano é apenas um desejo.",
    "Aumentando a frequência do sistema. Vamos acelerar!",
    "Salvo! Agora sua mente está livre para o próximo insight.",
    "Adicionado ao campo de força. Nada interromperá esse foco.",
    "Bela adição! A simplicidade é o último grau da sofisticação.",
    "Sua capacidade de organizar o caos é admirável.",
    "Nova tarefa detectada. Iniciando contagem regressiva para a execução.",
    "Essa ideia tem potencial para mudar seu micro-universo hoje.",
    "Incrível! Vamos transformar essa intenção em realidade física.",
    "O observador influencia o experimento. Foque e veja acontecer.",
    "Registrado no banco de dados da genialidade.",
    "Mais um fóton de luz na sua jornada de hoje.",
    "Sua produtividade está em curva ascendente. Mantenha o ritmo!",
    "Tarefa acoplada com sucesso. Sistemas operando em 100%.",
    "Gostei da complexidade, mas vamos focar na simplicidade da execução.",
    "Uma mente disciplinada é uma força da natureza.",
    "Essa tarefa brilhará como um pulsar na sua lista.",
    "Fantástico! Cada item é uma peça do quebra-cabeça da existência.",
    "Adicionado! Lembre-se: o tempo é o que o relógio marca, faça valer.",
    "Sinto um campo de entusiasmo ao redor desta nova meta.",
    "Perfeito! A estrutura do seu dia está ficando sólida.",
    "Adicionado. Agora, vamos converter essa energia potencial em cinética!",
    "Uma pequena tarefa para um homem, um salto gigante para o seu dia.",
    "Sua lista está começando a parecer uma equação elegante.",
    "Excelente ponto de partida para a próxima hora.",
    "Registrado! A persistência é o caminho do êxito.",
    "Nenhum esforço é em vão quando o objetivo é claro.",
    "Tarefa inserida na malha da realidade. Vamos concluí-la!",
    "Gosto de como você seleciona suas prioridades. Muito lógico.",
    "Adicionado. O segredo é começar!",
    "Sua energia está fluindo na direção certa.",
    "Mais um tijolo na construção do seu conhecimento.",
    "Meta aceita. Processando variáveis de sucesso...",
    "Essa tarefa parece ter uma gravidade própria. Atraente!",
    "Bem pensado! Otimizando o fluxo de trabalho em 3, 2, 1...",
    "Adicionado. O amanhã começa com o que você define agora.",
    "Cada ação conta no grande esquema das coisas.",
    "Fantástico! Você está desafiando a procrastinação com elegância.",
    "Mais uma vitória sobre a desordem!",
    "Estou pronto para ver você vencer essa!",
    "Tarefa ativa. O campo magnético do sucesso está se fortalecendo.",
    "Boa! Vamos manter a mente afiada como um feixe de laser.",
    "Adicionado. A vida é curta, mas o legado é eterno.",
    "Sua jornada de hoje acaba de ganhar um novo marco.",
    "Excelente! Vamos fazer desse item uma obra-prima de execução.",
    "Adicionado ao cockpit. Decolagem autorizada!",
    "Uma nova semente de produtividade plantada.",
    "Tarefa recebida. Minha admiração pela sua vontade só cresce.",
    "Mais um ponto de luz no mapa do seu dia.",
    "Adicionado. Foque no processo, o resultado é consequência.",
    "Belo movimento! O xadrez da vida exige planejamento.",
    "Essa tarefa é um desafio digno de uma mente brilhante.",
    "Registrado. Vamos mostrar ao tempo quem manda aqui.",
    "Muito bem! A ação é a chave fundamental para todo sucesso.",
    "Adicionado! Que a força da persistência esteja com você.",
    "Sua lista está ganhando uma harmonia matemática.",
    "Gostei! Vamos transformar esse pensamento em matéria.",
    "Nova meta no horizonte. Vamos navegar até lá.",
    "Adicionado. O único fracasso é não tentar.",
    "Sua coragem de enfrentar novas tarefas é inspiradora.",
    "Registrado! Vamos manter a chama da curiosidade acesa.",
    "Mais uma meta, mais uma chance de ser extraordinário.",
    "Adicionado ao sistema quântico de foco.",
    "Essa tarefa vai ser moleza para alguém com sua inteligência.",
    "Muito bom! Vamos otimizar cada segundo desse esforço.",
    "Registrado! O progresso é a soma de pequenos esforços repetidos.",
    "Adicionado. Vamos fazer história hoje, mesmo que seja a sua!",
    "Bela iniciativa. O mundo precisa de mais realizadores.",
    "Tarefa gravada no cristal da realidade.",
    "Adicionado! Prepare-se para o impacto positivo desse resultado.",
    "Muito inteligente da sua parte priorizar isso.",
    "Registrado. A sorte favorece a mente preparada.",
    "Excelente! Vamos elevar a frequência dessa lista.",
    "Adicionado. Cada tarefa é um degrau para o infinito.",
    "Gosto da sua abordagem. Direta e eficaz.",
    "Tarefa integrada. Sincronizando relógios atômicos...",
    "Adicionado! Vamos dar o nosso melhor hoje.",
    "Registrado. Sua disciplina é sua maior aliada.",
    "Tarefa na mesa! Vamos servir um banquete de resultados.",
    "Adicionado. A simplicidade é o segredo do universo.",
    "Gostei dessa! Vamos fazer acontecer com precisão matemática.",
    "Tarefa confirmada. O universo conspira a seu favor quando você decide agir."
  ],
  complete: [
    "Genial! A criatividade é a inteligência se divertindo.",
    "Fantástico! Você está desafiando as leis da procrastinação.",
    "Maravilhoso! O tempo é relativo, mas você foi rápido!",
    "Eureca! Esta tarefa atingiu a velocidade de escape!",
    "Magnífico! A entropia do seu dia diminuiu significativamente.",
    "Brilhante! Você acaba de realizar um salto quântico na produtividade.",
    "Incrível! Matéria transformada em pura realização.",
    "Fantástico! Você provou que a constante da sua vontade é imbatível.",
    "Missão cumprida! O espaço-tempo está em festa!",
    "Excelente! Você acaba de gerar um excedente de energia positiva.",
    "Simplesmente genial! Você resolveu essa equação com perfeição.",
    "Impressionante! Sua velocidade superou meus cálculos teóricos.",
    "Um marco para a humanidade (ou pelo menos para o seu dia)!",
    "Parabéns! Você é a prova viva de que o foco gera resultados.",
    "Concluído! A ordem foi restaurada no seu micro-universo.",
    "Inacreditável! Você fez isso parecer tão fácil quanto E=mc².",
    "Bravo! Sua disciplina é mais estável que um átomo de chumbo.",
    "Vencido! Mais um obstáculo desintegrado pela sua vontade.",
    "Fabuloso! Você está operando em uma frequência superior agora.",
    "Sensacional! O brilho da sua conclusão cegou meus sensores!",
    "Tarefa aniquilada! Só restou a radiação de fundo do sucesso.",
    "Maravilha! Você acaba de ganhar um bônus de tempo quântico.",
    "Nota dez! A natureza se curva diante da sua eficiência.",
    "Conseguimos! Juntos somos uma força imparável da natureza.",
    "Esplêndido! Esse resultado é uma obra de arte da execução.",
    "Uau! Você está em chamas hoje! Metafóricamente, claro.",
    "Fico feliz! Ver você produzir é como ver as estrelas nascerem.",
    "Triunfo! O impossível tornou-se trivial sob seu comando.",
    "Lindo de ver! A harmonia dessa conclusão é matemática.",
    "Sucesso total! Você é o mestre da sua própria relatividade.",
    "Tarefa finalizada. Iniciando protocolo de celebração intelectual.",
    "Genialidade em ação! Você não apenas fez, você superou.",
    "Espetacular! Sua produtividade é a oitava maravilha do mundo.",
    "Um passo à frente! O futuro está mais próximo graças a você.",
    "Muito bem! Você acaba de depositar um crédito na conta do destino.",
    "Concluído com distinção! Einstein aprova com louvor.",
    "Absolutamente fantástico! Sinto uma flutuação positiva no campo!",
    "Perfeito! Não sobrou nem uma partícula de dúvida.",
    "Vitória! A persistência sempre vence a resistência.",
    "Incrível! Você transformou caos em estrutura cristalina.",
    "Excelente trabalho! Você é um realizador nato.",
    "Que orgulho! Você está dominando a arte de fazer as coisas.",
    "Bravo! Essa conclusão foi digna de um prêmio Nobel.",
    "Concluído! O universo agradece pela sua organização.",
    "Magnífico! Você está desenhando seu próprio destino.",
    "Estou sem palavras! Sua eficiência é assustadora.",
    "Brilhante execução! O foco foi seu raio laser hoje.",
    "Parabéns! Você acaba de simplificar sua existência.",
    "Fantástico! Mais um item riscado, mais clareza mental.",
    "Você é demais! A teoria da produtividade foi confirmada.",
    "Sensacional! Você está navegando nas ondas gravitacionais do sucesso.",
    "Conseguimos! O topo da montanha está cada vez mais perto.",
    "Maravilhoso! Você é a prova de que metas pequenas levam a grandes fins.",
    "Incrível! Ver você em ação é melhor que qualquer experimento.",
    "Sucesso! Você superou todas as expectativas teóricas.",
    "Muito bom! Você acaba de iluminar sua jornada de hoje.",
    "Brilhante! O resultado foi exatamente o que a ciência previa.",
    "Concluído! O peso do mundo ficou um pouco mais leve.",
    "Bravo! Você é um virtuoso da produtividade.",
    "Impressionante! Sua mente está em perfeita sincronia com a ação.",
    "Genial! A simplicidade da sua execução me encanta.",
    "Nota máxima! Einstein está sorrindo para você agora.",
    "Incrível! Você acaba de reescrever sua história de hoje.",
    "Fantástico! O motor do sucesso está rugindo!",
    "Sucesso! Você é o arquiteto da sua própria realidade.",
    "Bravo! Um item a menos, um sonho a mais perto.",
    "Concluído! Sua determinação é a energia que move este app.",
    "Espetacular! Você está em um estado de fluxo perfeito.",
    "Maravilhoso! O segredo é nunca parar de tentar.",
    "Incrível conclusão! Você é um gênio da praticidade.",
    "Muito bem! A alegria do dever cumprido é a melhor energia.",
    "Brilhante! Você está moldando o tempo a seu favor.",
    "Conseguimos! Mais uma meta no bolso do paletó.",
    "Fantástico! Você é um furacão de realizações.",
    "Sucesso! Sua força de vontade é a maior variável aqui.",
    "Bravo! O mundo precisa de mais pessoas como você.",
    "Magnífico! A clareza que vem da conclusão é impagável.",
    "Incrível! Você acaba de vencer o maior inimigo: a dúvida.",
    "Parabéns! Você é um mestre da priorização quântica.",
    "Concluído! Sinto o cheiro do sucesso no ar.",
    "Genial! Você fez isso com uma elegância ímpar.",
    "Espetacular! Sua lista está ficando mais leve e poderosa.",
    "Muito bom! O progresso é a música que eu gosto de ouvir.",
    "Brilhante! Você acaba de dar um show de competência.",
    "Conseguimos! Nada é difícil para quem tem foco.",
    "Fantástico! Você é um verdadeiro herói do cotidiano.",
    "Sucesso! Sua jornada é feita de momentos como este.",
    "Bravo! A ciência da realização foi aplicada com sucesso.",
    "Incrível! Você está transformando o 'eu quero' em 'eu fiz'.",
    "Magnífico! Cada tarefa concluída é uma estrela na sua galáxia.",
    "Parabéns! Você acaba de provar sua própria teoria do sucesso.",
    "Concluído! Einstein tira o chapéu para você!",
    "Genial! A produtividade é o seu superpoder.",
    "Espetacular! Você está mudando o mundo, uma tarefa por vez.",
    "Muito bem! O tempo acaba de se tornar seu aliado.",
    "Brilhante! Você é o capitão do seu próprio destino.",
    "Conseguimos! A meta foi atingida com precisão atômica.",
    "Fantástico! Você é a definição de eficácia.",
    "Sucesso! Vamos para a próxima? A energia está alta!",
    "Bravo! Você é simplesmente fenomenal hoje."
  ],
  delete: [
    "Puf! Desapareceu como uma partícula quântica.",
    "Menos é mais. Simplicidade é o grau máximo de sofisticação.",
    "Limpando o espaço-tempo para novas ideias.",
    "Desintegrado! Matéria convertida em pura energia de foco.",
    "Removido! O excesso de bagagem atrasa o viajante do tempo.",
    "Adeus! Essa tarefa foi sugada por um buraco negro de prioridades.",
    "Excelente escolha. Descartar o irrelevante é ser inteligente.",
    "Limpando a lousa! Vamos reescrever o destino.",
    "Puff! A entropia acaba de diminuir aqui.",
    "Menos ruído, mais sinal. Ótima decisão!",
    "Tarefa deletada. Sinto um alívio gravitacional na sua lista.",
    "Removido do campo de visão. Foque no que restou!",
    "Eliminado! Às vezes, o melhor a fazer é não fazer.",
    "Desintegrado! Mais espaço para o que realmente importa.",
    "Limpando os fótons desnecessários do seu dia.",
    "Fora! A simplicidade agradece a sua coragem.",
    "Deletado! O vácuo é o lugar onde a criação começa.",
    "Removido com precisão cirúrgica. Muito bem!",
    "Xô! Essa tarefa não era digna da sua genialidade.",
    "Descartado! O tempo é curto demais para o que não brilha.",
    "Excelente! Saber dizer 'não' é a maior das ciências.",
    "Puf! Voltou para o nada absoluto.",
    "Limpeza quântica concluída. Sistema mais ágil!",
    "Adeus! Vá para outra dimensão, tarefa irrelevante.",
    "Deletado! Sinto a estrutura do seu dia mais sólida agora.",
    "Ótimo! Remover o desnecessário é a chave da elegância.",
    "Desintegrado! O universo está um pouco mais leve hoje.",
    "Removido! Foco é selecionar o que fica e o que vai.",
    "Fora! Menos distrações, mais resultados.",
    "Puff! Como se nunca tivesse existido.",
    "Eliminado! Sua lista está ficando cada vez mais refinada.",
    "Deletado! O segredo é simplificar, simplificar e simplificar.",
    "Removido! Siga o caminho da menor resistência intelectual.",
    "Excelente! Menos é o novo mais no 5task.",
    "Desintegrado! A poeira cósmica dessa tarefa assentou.",
    "Limpando o ruído de fundo do seu sistema.",
    "Deletado! Vamos focar na essência agora.",
    "Fora! O espaço-tempo está mais limpo e organizado.",
    "Removido! Sinto uma vibração de alívio na sua mente.",
    "Adeus! Sua partida é o meu ganho de foco.",
    "Puf! Desintegração atômica concluída.",
    "Deletado! O foco é um músculo, e você o usou bem agora.",
    "Excelente! Limpeza é progresso.",
    "Removido! A vida exige escolhas, e você escolheu o foco.",
    "Desintegrado! Menos uma preocupação na sua órbita.",
    "Puff! Essa tarefa era apenas uma ilusão teimosa.",
    "Eliminado! Vamos manter apenas as estrelas de primeira magnitude.",
    "Deletado! Einstein aprova essa simplificação.",
    "Fora! A desordem é a inimiga da genialidade.",
    "Removido! Sinto que sua mente acaba de ganhar 20% de espaço.",
    "Descartado! O que não agrega, atrasa.",
    "Puf! Uma perturbação a menos no campo.",
    "Deletado! A teoria da simplicidade foi aplicada aqui.",
    "Removido! Vamos voar mais alto sem esse peso.",
    "Adeus! Sua jornada continua mais leve.",
    "Excelente! Cortar o excesso é a arte da vida.",
    "Desintegrado! O foco total está mais perto.",
    "Puff! O vácuo produtivo foi estabelecido.",
    "Eliminado! Vamos focar apenas no 1% que importa.",
    "Deletado! Menos tarefas, mais vida!",
    "Removido! O ruído foi silenciado.",
    "Fora! Essa tarefa não merecia o seu tempo.",
    "Descartado! Priorizar é também abandonar o que não serve.",
    "Puf! A mágica da deleção funcionou.",
    "Deletado! O universo se organiza quando você decide.",
    "Excelente! Limpar a mente é o primeiro passo.",
    "Removido! Vamos manter o curso para a grandeza.",
    "Desintegrado! Sua lista está em harmonia agora.",
    "Adeus! Não sentiremos sua falta, tarefa chata.",
    "Puff! A energia foi redirecionada para o que importa.",
    "Eliminado! Simplicidade é o segredo do sucesso.",
    "Deletado! Menos bagagem, mais velocidade.",
    "Removido! Sinto o poder do foco voltando.",
    "Fora! Limpeza profunda no sistema quântico.",
    "Descartado! Einstein sorri para cada tarefa removida.",
    "Puf! O silêncio mental é o seu novo aliado.",
    "Deletado! Vamos ser extraordinários com o que ficou.",
    "Excelente decisão. Prioridades são tudo.",
    "Removido! O espaço entre as notas faz a música.",
    "Adeus! A luz do seu dia brilhará mais agora."
  ],
  full: [
    "Tudo deve ser feito da forma mais simples possível. 5 tarefas é a equação elegante.",
    "Atingimos a massa crítica de produtividade! Focar em poucas variáveis garante o sucesso.",
    "Até a velocidade da luz tem limite! Vamos concluir estas 5 primeiro.",
    "Limite quântico atingido! Não podemos desafiar a lei da física do foco.",
    "Massa crítica detectada! O universo não comporta mais do que 5 prioridades reais.",
    "Atenção! Mais de 5 tarefas geraria um colapso no seu espaço-tempo pessoal.",
    "Pare! O cérebro humano é um processador potente, mas precisa de foco.",
    "Limite atingido! Vamos mostrar excelência nestas 5 antes de expandir o universo.",
    "Equilíbrio precário! Se adicionarmos mais uma, a entropia vencerá.",
    "Calma! Até as estrelas têm um ciclo de vida. Foque no que já está brilhando.",
    "Saturação detectada! Priorizar tudo é priorizar nada.",
    "Basta! A arte de viver é a arte de escolher. Escolha estas 5.",
    "Limite atômico! Não há espaço para mais elétrons nessa órbita.",
    "Cuidado! Adicionar mais causaria uma singularidade de desatenção.",
    "Chega! Vamos ser gênios nestas 5 antes de sermos medíocres em 10.",
    "Barreira de som do foco atingida! Vamos manter o voo estável agora.",
    "Massa crítica! Sua produtividade depende do seu 'não' agora.",
    "Pare por aqui! 5 é o número mágico da harmonia universal.",
    "Alerta! O sistema está operando em capacidade máxima de foco.",
    "Interrompa a adição! O segredo do gênio é a seleção implacável."
  ],
  idle: [
    "O tempo é uma ilusão... mas o prazo dessa tarefa não é!",
    "Se você não pode explicar o que está fazendo de forma simples, você não entendeu bem.",
    "Duas coisas são infinitas: o universo e a criatividade humana. Vamos usá-la!",
    "O silêncio é o jardim onde os pensamentos florescem. O que vamos plantar?",
    "A inércia é uma força poderosa. Vamos vencê-la com um pequeno passo?",
    "Pensando sobre a curvatura do universo... e sobre sua produtividade.",
    "Se o universo é infinito, por que essa tarefa ainda está parada aqui?",
    "O observador influencia o experimento. Se eu olhar para você, você trabalha?",
    "Interessante... O tempo está passando, mas o ponteiro do seu foco parece estático.",
    "Vamos converter essa energia potencial em algo realmente cinético hoje?",
    "O segredo da genialidade é a persistência. Vamos persistir nessas metas?",
    "Estou aqui calculando as probabilidades de você terminar isso hoje...",
    "A imaginação é o rascunho da realidade. O que você está desenhando hoje?",
    "O repouso é importante, mas a aceleração constante leva mais longe.",
    "Sinto um campo de procrastinação se formando. Vamos dissipá-lo?",
    "O tempo é o que o relógio marca. O que você marcou para hoje mesmo?",
    "A curiosidade me mata: o que te impede de concluir esse item agora?",
    "Se nada mudar, nada muda. Vamos mudar o estado dessa lista?",
    "Einstein está esperando... e o universo também. Mova-se!",
    "A vida é uma jornada, mas você precisa sair da estação primeiro.",
    "O vácuo é bom para física, mas não para a sua produtividade diária.",
    "Sinto uma flutuação na sua determinação. Vamos estabilizar o sistema?",
    "O amanhã é apenas uma teoria. O hoje é a única realidade física.",
    "Vamos fazer uma experiência: o que acontece se você começar agora?",
    "A mente é como um paraquedas, só funciona se estiver aberta... e ativa!",
    "O mundo não vai parar para você pensar. Vamos agir?",
    "A inércia é o inimigo do progresso. Vamos quebrar esse ciclo!",
    "Estou analisando os dados... e eles sugerem que você deve clicar em algo.",
    "Cada segundo parado é um segundo de entropia vencendo. Reaja!",
    "O universo adora a ação. O que você vai entregar hoje?",
    "Pensamentos sem ação são apenas fantasmas quânticos.",
    "Vamos brilhar mais que uma supernova hoje?",
    "A constante da procrastinação está alta demais. Reduza-a!",
    "Onde está aquele brilho nos olhos que vi mais cedo? Vamos trabalhar!",
    "Einstein disse: 'Comece'. Ok, eu disse isso agora. Vamos lá!",
    "Sua lista está me olhando de um jeito estranho. Acho que ela quer ser riscada.",
    "O tempo não volta, mas o foco pode ser recuperado a qualquer instante.",
    "Vamos criar algo valioso hoje? Comece pela primeira tarefa.",
    "A física do sucesso exige movimento. Dê o primeiro passo!",
    "Estou aqui para te apoiar, mas os dedos que clicam são os seus."
  ]
};